package uk.tryzub.entity;
// Generated 09-Sep-2017 20:26:26 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer idcomment;
     private Publication publication;
     private User user;
     private String message;
     private Date date;
     private int rating;

    public Comment() {
    }

    public Comment(Publication publication, User user, String message, Date date, int rating) {
       this.publication = publication;
       this.user = user;
       this.message = message;
       this.date = date;
       this.rating = rating;
    }
   
    public Integer getIdcomment() {
        return this.idcomment;
    }
    
    public void setIdcomment(Integer idcomment) {
        this.idcomment = idcomment;
    }
    public Publication getPublication() {
        return this.publication;
    }
    
    public void setPublication(Publication publication) {
        this.publication = publication;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


