package uk.tryzub.entity;
// Generated 24-Jul-2017 19:32:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Dating generated by hbm2java
 */
public class Dating  implements java.io.Serializable {


     private Integer id;
     private String city;
     private Date date;
     private String email;
     private String message;
     private String name;
     private int section;

    public Dating() {
    }

    public Dating(String city, Date date, String email, String message, String name, int section) {
       this.city = city;
       this.date = date;
       this.email = email;
       this.message = message;
       this.name = name;
       this.section = section;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getSection() {
        return this.section;
    }
    
    public void setSection(int section) {
        this.section = section;
    }




}


