package uk.tryzub.entity;
// Generated 21-Sep-2017 22:51:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Event generated by hbm2java
 */
public class Event  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String location;
     private String contact;
     private Date date;
     private String photo;
     private String name;
     private String description;
     private Integer type;

    public Event() {
    }

	
    public Event(User user, String location, String contact, Date date, String name, String description) {
        this.user = user;
        this.location = location;
        this.contact = contact;
        this.date = date;
        this.name = name;
        this.description = description;
    }
    public Event(User user, String location, String contact, Date date, String photo, String name, String description, Integer type) {
       this.user = user;
       this.location = location;
       this.contact = contact;
       this.date = date;
       this.photo = photo;
       this.name = name;
       this.description = description;
       this.type = type;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }




}


