package uk.tryzub.entity;
// Generated 22-Aug-2017 20:47:48 by Hibernate Tools 4.3.1



/**
 * Groupofuser generated by hbm2java
 */
public class Groupofuser  implements java.io.Serializable {


     private String username;
     private String groupname;

    public Groupofuser() {
    }

    public Groupofuser(String username, String groupname) {
       this.username = username;
       this.groupname = groupname;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getGroupname() {
        return this.groupname;
    }
    
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }




}


