package uk.tryzub.entity;
// Generated 04-Sep-2017 16:53:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Groupoftopic generated by hbm2java
 */
public class Groupoftopic  implements java.io.Serializable {


     private Integer idgroupoftopic;
     private String name;
     private Set topics = new HashSet(0);

    public Groupoftopic() {
    }

	
    public Groupoftopic(String name) {
        this.name = name;
    }
    public Groupoftopic(String name, Set topics) {
       this.name = name;
       this.topics = topics;
    }
   
    public Integer getIdgroupoftopic() {
        return this.idgroupoftopic;
    }
    
    public void setIdgroupoftopic(Integer idgroupoftopic) {
        this.idgroupoftopic = idgroupoftopic;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getTopics() {
        return this.topics;
    }
    
    public void setTopics(Set topics) {
        this.topics = topics;
    }




}


