package uk.tryzub.entity;
// Generated 06-Sep-2017 21:15:34 by Hibernate Tools 4.3.1



/**
 * Habitation generated by hbm2java
 */
public class Habitation  implements java.io.Serializable {


     private Integer id;
     private int type;
     private String address;
     private String photo;
     private String description;
     private String phone;
     private String email;

    public Habitation() {
    }

	
    public Habitation(int type, String address, String description, String email) {
        this.type = type;
        this.address = address;
        this.description = description;
        this.email = email;
    }
    public Habitation(int type, String address, String photo, String description, String phone, String email) {
       this.type = type;
       this.address = address;
       this.photo = photo;
       this.description = description;
       this.phone = phone;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


