package uk.tryzub.entity;
// Generated 06-Sep-2017 21:15:34 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Habitation generated by hbm2java
 */
public class Habitation  implements java.io.Serializable {


     private Integer id;
     private User user;
     private int type;
     private String address;
     private String photo;
     private String description;
     private String contact;
     private Date date;

    public Habitation() {
    }

	
    public Habitation(User user, int type, String address, String description, String contact, Date date) {
        this.user = user;
        this.type = type;
        this.address = address;
        this.description = description;
        this.contact = contact;
        this.date = date;
    }
    public Habitation(User user, int type, String address, String photo, String description,  String contact, Date date) {
       this.user = user;
       this.type = type;
       this.address = address;
       this.photo = photo;
       this.description = description;
       this.contact = contact;
       this.date = date;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getType() {
        return this.type;
    }
    
    public void setType(int type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
   
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


