package uk.tryzub.entity;
// Generated 05-Aug-2017 20:30:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private Integer idorganization;
     private String name;
     private String section;
     private String address;
     private String description;
     private String contact;
     private byte[] photo;
     private Set reviews = new HashSet(0);

    public Organization() {
    }

	
    public Organization(String name, String section) {
        this.name = name;
        this.section = section;
    }
    public Organization(String name, String section, String address, String description, String contact, byte[] photo, Set reviewses) {
       this.name = name;
       this.section = section;
       this.address = address;
       this.description = description;
       this.contact = contact;
       this.photo = photo;
       this.reviews = reviews;
    }
   
    public Integer getIdorganization() {
        return this.idorganization;
    }
    
    public void setIdorganization(Integer idorganization) {
        this.idorganization = idorganization;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSection() {
        return this.section;
    }
    
    public void setSection(String section) {
        this.section = section;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public byte[] getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }
    public Set getReviews() {
        return this.reviews;
    }
    
    public void setReviews(Set reviews) {
        this.reviews = reviews;
    }




}


