package uk.tryzub.entity;
// Generated 24-Jul-2017 19:32:25 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer postid;
     private Topic topic;
     private User user;
     private String text;
     private Date date;

    public Post() {
    }

    public Post(Topic topic, User user, String text, Date date) {
       this.topic = topic;
       this.user = user;
       this.text = text;
       this.date = date;
    }
   
    public Integer getPostid() {
        return this.postid;
    }
    
    public void setPostid(Integer postid) {
        this.postid = postid;
    }
    public Topic getTopic() {
        return this.topic;
    }
    
    public void setTopic(Topic topic) {
        this.topic = topic;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


