package uk.tryzub.entity;
// Generated 05-Aug-2017 20:30:17 by Hibernate Tools 4.3.1



/**
 * Reviews generated by hbm2java
 */
public class Reviews  implements java.io.Serializable {


     private Integer idreview;
     private Organization organization;
     private String review;

    public Reviews() {
    }

    public Reviews(Organization organization, String review) {
       this.organization = organization;
       this.review = review;
    }
   
    public Integer getIdreview() {
        return this.idreview;
    }
    
    public void setIdreview(Integer idreview) {
        this.idreview = idreview;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public String getReview() {
        return this.review;
    }
    
    public void setReview(String review) {
        this.review = review;
    }




}


