package uk.tryzub.entity;
// Generated 11-Aug-2017 12:48:46 by Hibernate Tools 4.3.1

import java.util.Date;




/**
 * Review generated by hbm2java
 */
public class Review  implements java.io.Serializable {


     private Integer idreview;
     private Organization organization;
     private User user;
     private String comment;
     private Date date;

    public Review() {
    }

    public Review(Organization organization, User user, String comment, Date date) {
       this.organization = organization;
       this.user = user;
       this.comment = comment;
       this.date = date;
    }
   
    public Integer getIdreview() {
        return this.idreview;
    }
    
    public void setIdreview(Integer idreview) {
        this.idreview = idreview;
    }
    public Organization getOrganization() {
        return this.organization;
    }
    
    public void setOrganization(Organization organization) {
        this.organization = organization;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


