package uk.tryzub.entity;
// Generated 24-Jul-2017 19:32:25 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic implements java.io.Serializable {

    private Integer topicid;
    private User user;
    private String name;
    private int answers;
    private int views;
    private String last;
    private Set posts = new HashSet(0);

    public Topic() {
    }

    public Topic(User user, String name, int answers, int views, String last) {
        this.user = user;
        this.name = name;
        this.answers = answers;
        this.views = views;
        this.last = last;
    }

    public Topic(User user, String name, int answers, int views, String last, Set posts) {
        this.user = user;
        this.name = name;
        this.answers = answers;
        this.views = views;
        this.last = last;
        this.posts = posts;
    }

    public Topic(int topicid, User user, String name, int answers, int views, String last, Set posts) {
        this.topicid = topicid;
        this.user = user;
        this.name = name;
        this.answers = answers;
        this.views = views;
        this.last = last;
        this.posts = posts;
    }

    public Integer getTopicid() {
        return this.topicid;
    }

    public void setTopicid(Integer topicid) {
        this.topicid = topicid;
    }

    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getAnswers() {
        return this.answers;
    }

    public void setAnswers(int answers) {
        this.answers = answers;
    }

    public int getViews() {
        return this.views;
    }

    public void setViews(int views) {
        this.views = views;
    }

    public String getLast() {
        return this.last;
    }

    public void setLast(String last) {
        this.last = last;
    }

    public Set getPosts() {
        return this.posts;
    }

    public void setPosts(Set posts) {
        this.posts = posts;
    }
    
    

}
