package uk.tryzub.entity;
// Generated 10-Aug-2017 20:22:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Organization generated by hbm2java
 */
public class Organization  implements java.io.Serializable {


     private Integer idorganization;
     private Section section;
     private User user;
     private String name;
     private String address;
     private String description;
     private String contact;
     private String photo;
     private Set reviewses = new HashSet(0);

    public Organization() {
    }

	
    public Organization(Section section, User user, String name) {
        this.section = section;
        this.user = user;
        this.name = name;
    }
    public Organization(Section section, User user, String name, String address, String description, String contact, String photo, Set reviewses) {
       this.section = section;
       this.user = user;
       this.name = name;
       this.address = address;
       this.description = description;
       this.contact = contact;
       this.photo = photo;
       this.reviewses = reviewses;
    }
   
    public Integer getIdorganization() {
        return this.idorganization;
    }
    
    public void setIdorganization(Integer idorganization) {
        this.idorganization = idorganization;
    }
    public Section getSection() {
        return this.section;
    }
    
    public void setSection(Section section) {
        this.section = section;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    public Set getReviewses() {
        return this.reviewses;
    }
    
    public void setReviewses(Set reviewses) {
        this.reviewses = reviewses;
    }




}


